### ISSUE TITLE
P3 - Portal signin page: Italian wording

### ISSUE THREAD

**Issue by vdinicola** [DavideDiCarlo/VillaItalia#23]
See attached screenshot

1) Rename "Accedi" as "Sign In"
2) Rename "Indirizzo e-mail" simply as email
![portal](https://cloud.githubusercontent.com/assets/2458919/7338656/839e9734-ec53-11e4-88ad-b777b29c927b.png)

**Comment by DavideDiCarlo** [comment]
fixed on merge #31
