### ISSUE TITLE
P1 - Portal. Vintage year needs to be improved

### ISSUE THREAD

**Issue by vdinicola** [DavideDiCarlo/VillaItalia#25]
1) Vintage is only a year (e.g. 1998). We may want to to keep it as a datetime format in the database. However, be sure that only the year is shown/edited/updated in the portal and the website

2) Currently, I cannot choose a year beneath 2010. That's bad

**Comment by DavideDiCarlo** [comment]
Fixed on merge #31, vintage is now an integer
