### ISSUE TITLE
P3 - Portal  Highlight in Green when an action is successful

### ISSUE THREAD

**Issue by vdinicola** [DavideDiCarlo/VillaItalia#26]
See attached screenshot.
After creating a new wine, I should see a bigger and "greener" success message
![highlight](https://cloud.githubusercontent.com/assets/2458919/7338712/0c30dd18-ec55-11e4-9627-5a21b1c7d626.png)

**Comment by DavideDiCarlo** [comment]
Fixed on merge #31
