### ISSUE TITLE
P2 - Portal. Introduce a maximum byte size and format for the wine picture

### ISSUE THREAD

**Issue by vdinicola** [DavideDiCarlo/VillaItalia#28]
We cannot allow the admin to upload a 3MB picture. Let's put a reasonable limit to 50KB.

Also, enfore to picture to be .jpeg/.jpg or .png

**Comment by vdinicola** [comment]
Of course, write it explicitily in the portal that the picture must be .jpeg/.jpg or .png and max 50KB, so noone will ever forget it

**Comment by DavideDiCarlo** [comment]
Fixed on merge #31
