### ISSUE TITLE
P1 - Upon signing up, show a Green-highlighted message saying "Please check your email to complete registration"

### ISSUE THREAD

**Issue by vdinicola** [DavideDiCarlo/VillaItalia#64]
Right now, when a user signs up for the first time, upon pressing the "Sign up" button, s/he is redirected to the Home Page. It's very unclear for him/her understand what's going on

**Comment by DavideDiCarlo** [comment]
we had already done :+1: 
Look at the top of the page
![screen](https://cloud.githubusercontent.com/assets/7901246/7913714/6e25ca68-0872-11e5-9574-d995148a9082.png)
