### ISSUE TITLE
P1 - Do not force to use Rails 4.0.4

### ISSUE THREAD

**Issue by vdinicola** [DavideDiCarlo/VillaItalia#8]
Your Gemfile forces users to install Rails at its exact version 4.0.4
Instead, allow users with a greater Rails version number (currently 4.2.1) to run your code.
Simply add a ">=" in your Gemfile, like shown below:

###########
gem 'rails', '>= 4.0.4'
###########

Steps to follow:
1) Edit the Gemfile as shown just above
2) Delete the Gemfile.lock
3) Run "sudo bundle install"
4) Checkin the modified Gemfile and Gemfile.lock

**Comment by DavideDiCarlo** [comment]
Done on merge #10 :+1:
